[#12] 폴더 구조 변경
gdsc-ssu/up-date-cli pull request #13
Opened 2023-07-16 07:00 UTC by halfmoon-mind

## Summary
기능 추가는 없이, 패키지 내부에 폴더 구조를 변경하였습니다.

## Check List

- [x] PR 제목을 commit convention에 맞게 작성
- [x] reviewer 추가

## Issue

- close #12 

## Test
테스팅 영상은 없습니다.

2023-07-16 16:05 UTC, hoyyChoi requested changes

2023-07-16 16:05 UTC, hoyyChoi commented on source/app.js
> +import Register from './register.js';
혹시 이 부분 파일명은 왜 바꾸신건가요?? 에러나지않나요?

2023-07-16 16:05 UTC, hoyyChoi commented on source/Search.js
> +				});
TypeMovie 함수가 파리미터 받고 있어서 이렇게 수정하면 에러나지 않나요??

2023-07-16 16:49 UTC, halfmoon-mind commented on test.js
테스팅 파일 파일이 필요해보였는데, 사실 처음 Github Action 설정하다가 테스트에서 계속 에러 나서 그냥 화나서 빼버렸는데, 하다보니 그냥 커맨드 하나 빼면 됬던 거라, 나중에 테스팅 코드 넣으려면 필요해보여서 추가했습니다!

2023-07-16 16:51 UTC, halfmoon-mind commented on source/app.js
> +import Register from './register.js';
음 사실 처음에 컨벤션 같은걸 모두 정하지 않았다 보니, app.js나 다른 파일들과 통일성이 없는 것이 눈에 보여서 이름들을 모두 소문자로 시작하는 형태로 수정했습니다! (아마 기존에 있는 파일들도 이름은 바꿔서 실행과 관련된 부분들은 상관 없을거에요!)

2023-07-16 16:53 UTC, halfmoon-mind commented on source/Search.js
> +				});
아 컨플릭트 해결하면서 이 부분이 잘못 수정된거 같아요 코멘트 감사합니다!!!

2023-07-17 05:31 UTC, halfmoon-mind commented on source/app.js
> +import Register from './register.js';
아하 github에서는 파일 이름 변경점이 보이지 않는군요...

2023-07-17 09:11 UTC, hoyyChoi commented on source/app.js
> +import Register from './register.js';
네 그래서 여쭤봤습니다!

2023-07-17 09:12 UTC, hoyyChoi approved these changes

2023-07-17 09:21 UTC, merged